### ISSUE TITLE
Rename `tagging` to `modules`

### ISSUE THREAD

**Issue by rainerhahnekamp** [softarc-consulting/sheriff#140]

**Comment by michael-small** [comment]
The configs for the tests projects still use `tagging` as well as `version: 1`. Example: https://github.com/softarc-consulting/sheriff/blob/main/test-projects/angular-i/sheriff.config.ts

Is there a legacy reason those didn't get renamed or did those just get missed? I can make a PR if they just need to be updated. Those projects were the first thing I tried since after reading the docs and trying to get a hang of it, so I assume that is what they are for to be referenced.

**Comment by rainerhahnekamp** [comment]
Hey @michael-small, that test verifies that `tagging` still works, but I think `angular-iv` deserves a renaming to `modules`. Feel free to open a PR
