### ISSUE TITLE
circular dependency

### ISSUE THREAD

**Issue by korneliusz-w** [softarc-consulting/sheriff#57]
Hey

I have problem with circular dependecy.

Folder structure
![image](https://github.com/softarc-consulting/sheriff/assets/4181722/3605699f-5736-4525-a083-5a1049f97450)

Domain: users; type: shared

Inside index.ts
![image](https://github.com/softarc-consulting/sheriff/assets/4181722/ad7a5fd5-a8e2-4bc2-9b75-699b3fc16917)

sheriff
![image](https://github.com/softarc-consulting/sheriff/assets/4181722/38b17356-ea09-4923-b57e-24cbc2a2092d)
depRules:
![image](https://github.com/softarc-consulting/sheriff/assets/4181722/168d1038-d0bd-4f77-af56-eb08d44f6cdc)

So I want to use one model inside another
![image](https://github.com/softarc-consulting/sheriff/assets/4181722/565c46fc-6ecc-4086-8c8e-8a4c7863b03a)

But now I have cirucular dependencies to index.ts

I can change import path to
![image](https://github.com/softarc-consulting/sheriff/assets/4181722/0b73e6e3-41b6-409f-82f1-f8f5be4a188b)
but in this way I can remove sheriff rule and it will be still working
![image](https://github.com/softarc-consulting/sheriff/assets/4181722/a02c3304-dbe7-416b-a247-ab9e93c5f8c9)

It's not quite clear to me how it should be configured.

**Comment by rainerhahnekamp** [comment]
Hi, can you please confirm that?

But it looks to me that both `User` and `GetUserRequests` are part of the same module, which is 'src/domains/user/shared/model'?

If yes, you should have `import {User} from './user'` because have a dependency within the same module.

The `'type:shared: []`means that a module of type shared cannot have any dependency to any other module.

`'type:shared': ['type:shared']` only makes sense, if you would have multiple modules of `type:shared`. You would enable here, that these module can depend on each other.

Makes sense or do you need more info?

**Comment by korneliusz-w** [comment]
Hey. Thanks for answer and better explanation how does it work.

**Comment by rainerhahnekamp** [comment]
You're welcome. I'm closing the issue now, if you have remaining questions, please let me know.
